version: '3'
services:
    database:
        container_name: database
        build: ./database
        ports:
            - '27017:27017' # expose:container
        volumes:
            - ./database/mongodb:/data/db

    backend:
        container_name: backend
        tty: true
        build: ./backend
        ports:
            - '4000:4000'
        volumes:
            - './backend:/usr/src/app'
            - '/usr/src/app/node_modules'
        depends_on:
            - database
        links:
            - database
        environment:
            - PORT=4000
            - DATABASE_URL=mongodb://database:27017/preactoy
            - TEST_DATABASE_URL=mongodb://database:27017/preactoy-test
            - TOKEN_SECRET=SECRET!@#!
            # - DEBUG=server:*
    frontend:
        container_name: frontend
        build: ./frontend
        ports:
            - '3000:3000'
        volumes:
            - './frontend:/usr/src/app'
            - '/usr/src/app/node_modules'
        depends_on:
            - backend
        links:
            - backend
        environment:
            - PORT=3000
