---
swagger: "2.0"
info:
    description: "PReacToy Backend APIs"
    version: "1.0.0"
    title: "Backend APIs"
host: "localhost:4000"
basePath: "/api"
schemes:
    - "http"
produces:
    - "application/json"
